"""Rich terminal, JSON, and Markdown output formatters for polaroid."""

from __future__ import annotations

import json

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from polaroid.graph import MergeResult, SceneEdge, SceneNode

_console = Console()


def _truncate(text: str, max_len: int = 72) -> str:
    return text if len(text) <= max_len else text[: max_len - 1] + "…"


def print_scene(
    nodes: list[SceneNode],
    console: Console | None = None,
) -> None:
    """Print a scene node list to the terminal using Rich.

    Args:
        nodes:   List of SceneNode objects to display.
        console: Optional Rich Console (defaults to stdout).
    """
    con = console or _console

    if not nodes:
        con.print("[dim]No nodes in scene.[/dim]")
        return

    con.print(
        Panel(
            f"[bold cyan]Scene Graph — {len(nodes)} node(s)[/bold cyan]",
            expand=False,
            border_style="cyan",
        )
    )
    con.print()

    table = Table(show_header=True, header_style="bold", box=None, padding=(0, 1))
    table.add_column("ID", width=16)
    table.add_column("Label", width=24)
    table.add_column("Type", width=12)
    table.add_column("Conf", width=6)
    table.add_column("Agent", width=12)

    for node in nodes:
        table.add_row(
            Text(node.id, style="dim"),
            _truncate(node.label, 24),
            node.node_type,
            f"{node.confidence:.2f}",
            _truncate(node.agent_id, 12) if node.agent_id else "-",
        )

    con.print(table)
    con.print()


def print_merge(
    result: MergeResult,
    console: Console | None = None,
) -> None:
    """Print a MergeResult to the terminal using Rich.

    Args:
        result:  MergeResult from SceneMerger.merge().
        console: Optional Rich Console (defaults to stdout).
    """
    con = console or _console

    con.print(
        Panel(
            f"[bold green]Merge complete[/bold green]  "
            f"[dim]+{len(result.added_nodes)} nodes · "
            f"~{len(result.updated_nodes)} updated · "
            f"+{len(result.added_edges)} edges · "
            f"{result.conflicts_resolved} conflict(s) resolved[/dim]",
            expand=False,
            border_style="green",
        )
    )

    if result.added_nodes:
        con.print("[bold]Added nodes:[/bold]")
        for node in result.added_nodes[:10]:
            con.print(f"  + [cyan]{node.label}[/cyan] ({node.node_type})")
        if len(result.added_nodes) > 10:
            con.print(f"  … and {len(result.added_nodes) - 10} more")

    if result.updated_nodes:
        con.print("[bold]Updated nodes (higher confidence):[/bold]")
        for node in result.updated_nodes[:5]:
            con.print(f"  ~ [yellow]{node.label}[/yellow] conf={node.confidence:.2f}")

    con.print()


def to_json(
    nodes: list[SceneNode],
    edges: list[SceneEdge] | None = None,
) -> str:
    """Serialize nodes (and optionally edges) to JSON.

    Args:
        nodes: List of SceneNode objects.
        edges: Optional list of SceneEdge objects.

    Returns:
        Indented JSON string.
    """
    data: dict = {
        "node_count": len(nodes),
        "nodes": [n.to_dict() for n in nodes],
    }
    if edges is not None:
        data["edge_count"] = len(edges)
        data["edges"] = [e.to_dict() for e in edges]
    return json.dumps(data, indent=2)


def to_markdown(nodes: list[SceneNode]) -> str:
    """Generate a Markdown table of scene nodes.

    Args:
        nodes: List of SceneNode objects.

    Returns:
        Markdown string suitable for documentation or PR comments.
    """
    if not nodes:
        return "## polaroid scene graph\n\n_No nodes in scene._\n"

    lines = [
        "## polaroid scene graph",
        "",
        f"**{len(nodes)} node(s)** in scene.",
        "",
        "| ID | Label | Type | Confidence | Agent |",
        "|----|-------|------|-----------|-------|",
    ]
    for node in nodes[:50]:
        agent = node.agent_id or "-"
        lines.append(
            f"| `{node.id}` | {node.label} | {node.node_type} "
            f"| {node.confidence:.2f} | {agent} |"
        )

    if len(nodes) > 50:
        lines.append(f"| … | *{len(nodes) - 50} more* | | | |")

    lines += [
        "",
        "*Generated by [polaroid](https://github.com/sandeep-alluru/polaroid)*",
    ]
    return "\n".join(lines)
